CREATE OR REPLACE FUNCTION CO2_DB.HARMONIZED_CO2.CALCULATE_SEASONAL_VARIATION()
RETURNS TABLE (
    MONTH INT,
    AVG_CO2_PPM FLOAT,
    DEVIATION_FROM_ANNUAL_MEAN FLOAT
)
AS
$$
    WITH annual_mean AS (
        SELECT AVG(CO2_PPM) AS mean
        FROM CO2_DB.HARMONIZED_CO2.CO2_EMISSIONS_HARMONIZED
    ),
    monthly_avg AS (
        SELECT 
            EXTRACT(MONTH FROM DATE)::INT AS MONTH,
            AVG(CO2_PPM) AS AVG_CO2_PPM
        FROM CO2_DB.HARMONIZED_CO2.CO2_EMISSIONS_HARMONIZED
        GROUP BY EXTRACT(MONTH FROM DATE)
    )
    SELECT 
        m.MONTH,
        m.AVG_CO2_PPM,
        m.AVG_CO2_PPM - a.mean AS DEVIATION_FROM_ANNUAL_MEAN
    FROM monthly_avg m, annual_mean a
    ORDER BY m.MONTH
$$;

